CredentialSchema:
  sumologic:
    access_id:
      type: string
      description: Your access ID to connect to the Sumologic API with
    access_key:
      type: string
      description: Your access key to connect to the Sumologic API with
    endpoint:
      type: url|null
      description: The API endpoint to use. Defaults https://api.sumologic.com/api/v1/ if empty
Cache:
  sumologic: Symfony\Component\Cache\Adapter\FilesystemAdapter
